### create a payment
POST http://localhost:8080/finance/makeTransaction
Content-Type: application/json

{
    "amount" :200000,
    "studentId": 2
}

### get transcation historuy
GET http://localhost:8080/finance/getTransactionHistory

### get student installments
GET http://localhost:8080/finance/getInstallmentsByStudent/1


### get transactions by period

GET http://localhost:8080/finance/getTransactionsByDate/2024-06-11/2023-06-11

### update student by id
PUT  http://localhost:8080/finance/updateTransactionById/2
Content-Type: application/json

{
    "amount": 300000
}

### deleting a finance transaction 
DELETE http://localhost:8080/finance/deleteTransactionById/12