### get payment ledger
GET http://localhost:8080/payment/getLedger


### get student student balances
GET http://localhost:8080/payment/getStudentBalances/5000000

### get balance for one student
GET http://localhost:8080/payment/getBalanceForOneStudent/1/5000000