### get payment ledger
GET http://46.101.198.244:8096/payment/getLedger


### get student student balances
GET http://46.101.198.244:8096/payment/getStudentBalances/4000000

### get balance for one student
GET http://46.101.198.244:8096/payment/getBalanceForOneStudent/2/3000000