GET http://46.101.198.244:8096/student/getAllStudents

### posting students
POST http://46.101.198.244:8096/student/addStudent
Content-Type: application/json

{
    "firstName": "Ntanda",
    "lastName": "Nassar",
    "email": "ntandaNasser@gmail.com",
    "password": "ntanda@256",
    "year": 4,
    "gender": "Male"
}

### delete student
DELETE http://46.101.198.244:8096/student/deleteStudentById/15


### upadting a student
PUT http://46.101.198.244:8096/student/updateStudentById/4
Content-Type: application/json

{
    "lastName": "Morgan"
}

### get studentBy Id -- this has issues
GET http://46.101.198.244:8096/student/getOneStudentById/1

### authenticate user 
GET http://46.101.198.244:8096/student/authenticateUserByEmailAndPassword/kisituwilfred@gmail.com/wilfred@256